# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  name: docs
  description: Dokumentation für das urvent Veranstaltungssystem
  homepage: https://docs.urvent.com
  topics: documentation

  default_branch: main
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false

labels:
  - name: automerge
    color: ededed
  - name: docs
    color: fbca04
  - name: help wanted
    color: 159818
  - name: invalid
    color: e6e6e6
  - name: pedantic
    color: DDDDDD
  - name: bug
    color: fc2929
  - name: feature
    color: 0e8a16
  - name: question
    color: cc317c

branches:
  - name: main
    protection:
      enforce_admins: falser
      required_status_checks:
        contexts:
          - "Lint / DOCtor-RST"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
