on: [push, pull_request]

name: Lint

jobs:
  build:
    name: 'Build'

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Python 3.7"
        uses: actions/setup-python@v1
        with:
          python-version: '3.7' # Semantic version range syntax or exact version of a Python version

      - name: "Display Python version"
        run: python -c "import sys; print(sys.version)"

      - name: "Install Sphinx dependencies"
        run: sudo apt-get install python-dev build-essential

      - name: "Install custom requirements via pip"
        run: pip install -r requirements.txt

      - name: "Build documentation"
        run: sphinx-build -W -b html -d _build/doctrees . _build/html

  doctor-rst:
    name: 'DOCtor-RST'

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "DOCtor-RST"
        uses: docker://oskarstark/doctor-rst
        with:
          args: --short
